net:
  port: 27017
  bindIp: 0.0.0.0
  tls:
    mode: requireTLS
    certificateKeyFile: /certs/mongo/mongo.pem
    CAFile: /certs/mongo/ca.crt
    allowConnectionsWithoutCertificates: true

security:
  authorization: "enabled"
